version: '2'

services:
  mysql:
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=url_db
      - MYSQL_USER=flask
      - MYSQL_PASSWORD=f1ask
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: web_app
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./web_app:/var/www/url_shortener/web_app
    ports:
      - "80:80"
      - "443:443"
